isi-vista/adam

adam/learner.py, adam/perception/__init__.py, tests/pipeline_test.py
This representation allows us to learn actions.
Closes #24
=> Represent perceptions as sequences of perception frames

adam/ontology/__init__.py, adam/perception/developmental_primitive_perception.py, docs/index.rst, tests/perception/developmental_primitive_perception.py, tests/perception/developmental_primitive_perception_test.py
Addresses but does not complete #63
=> Start of developmental primitive perceptual representation

adam/perception/perception_frame_difference.py, tests/perception/developmental_primitive_perception_test.py
The class computes 6 different sets for added and removed objects, relations, and assertions. Would be great if you could check whether the class hierarchy is as needed.
=> Class to compute differences between perception frames

adam/ontology/__init__.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/situation/__init__.py, docs/index.rst, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
Right now it only makes perceived objects for situation objects and
their components and copies over all relations between objects
and their components directly into the perceptual representation.
=> Minimal perceptual generation

adam/curriculum/phase1_curriculum.py, adam/language_specific/english/english_language_generator.py, adam/ontology/phase1_ontology.py, adam/perception/developmental_primitive_perception.py, adam/situation/templates/phase1_templates.py, tests/perception/developmental_primitive_perception_test.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Represent the learner itself in the perception representation.

adam/ontology/phase1_ontology.py
=> Adds 'hollow' as a perceivable property

adam/ontology/__init__.py, adam/ontology/ontology.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/situation/high_level_semantics_situation.py, adam/situation/templates/phase1_templates.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py, tests/situation/templates/phase1_template_test.py
=> Bind action variables which are not bound by semantic roles

adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> 121 negation of relations while translating actions to perceptions

adam/language_specific/english/english_language_generator.py, tests/language_specific/english/test_english_language_generator.py
=> using I in language generator

adam/curriculum_to_html.py, adam/language_specific/english/english_language_generator.py, adam/language_specific/english/english_phase_1_lexicon.py, tests/language_specific/english/test_english_language_generator.py
Closes https://github.com/isi-vista/adam/issues/151
=> Refine Color display as HEX & Language Description

adam/language_specific/english/english_language_generator.py, adam/ontology/phase1_ontology.py, tests/language_specific/english/test_english_language_generator.py
=> using the subject pronoun you in language generator

adam/ontology/phase1_ontology.py
=> Add relationship to the ground to semantics of fly, jump, etc.

adam/curriculum_to_html.py, tests/curriculum_to_html_test.py
=> Make index of instance groups in curriculum dump

adam/curriculum_to_html.py
Example of output in HTML document:
Closes https://github.com/isi-vista/adam/issues/178
=> Perceived Objects nested by PartOf relationship in HTML Layout

adam/curriculum_to_html.py
Example in HTML display:
Closes https://github.com/isi-vista/adam/issues/187
=> Add Regions as Nested Bullets under Perceived Objects

adam/curriculum/phase1_curriculum.py, adam/language/dependency/__init__.py, adam/language_specific/english/english_language_generator.py, adam/language_specific/english/english_syntax.py, adam/ontology/phase1_ontology.py, adam/ontology/phase1_spatial_relations.py, adam/situation/templates/phase1_templates.py, tests/language_specific/english/test_english_language_generator.py
=> Add first templates for spatial relations

adam/ontology/ontology.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py
Completes bullet point two of https://github.com/isi-vista/adam/issues/83
=> Add Prototypical Size to Perception Generation

adam/ontology/action_description.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/relation.py, adam/situation/high_level_semantics_situation.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
Closes https://github.com/isi-vista/adam/issues/102
=> Introduce Speaker Focus to Ontology, Situation, and Perception. 

adam/curriculum/phase1_curriculum.py, adam/language_specific/english/english_language_generator.py, adam/language_specific/english/english_syntax.py, adam/situation/high_level_semantics_situation.py, adam/situation/templates/phase1_templates.py, tests/language_specific/english/test_english_language_generator.py
=> Allow situations to carry hints about their syntactic realization.

adam/curriculum/phase1_curriculum.py, adam/situation/templates/phase1_templates.py
=> Add a curriculum template for X on Y

adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> rename GAZE to GAZED-AT

adam/curriculum/phase1_curriculum.py
=> templates for liquids in containers

adam/ontology/action_description.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Dowty's proto-roles

adam/curriculum/phase1_curriculum.py, adam/ontology/phase1_ontology.py, tests/curriculum/phase1_curriculum_test.py, tests/language_specific/english/test_english_language_generator.py
Closes https://github.com/isi-vista/adam/issues/202
=> Add "eat" NP Curriculum

adam/curriculum/phase1_curriculum.py, adam/language_specific/english/english_language_generator.py, adam/ontology/__init__.py, adam/ontology/ontology.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/situation/high_level_semantics_situation.py, adam/situation/templates/phase1_templates.py, tests/curriculum/phase1_curriculum_test.py, tests/situation/situation_test.py, tests/situation/templates/phase1_template_test.py
=> Forbid multiple instances of the same recognized particular

adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Ensuring learner perception

adam/curriculum/phase1_curriculum.py, adam/language_specific/english/english_language_generator.py, adam/ontology/phase1_ontology.py, adam/situation/templates/phase1_templates.py, tests/curriculum/phase1_curriculum_test.py, tests/language_specific/english/test_english_language_generator.py
Closes https://github.com/isi-vista/adam/issues/207
=> Refactor and Extend Fall Curriculum Generation 

adam/curriculum/phase1_curriculum.py, adam/language_specific/english/english_phase_1_lexicon.py, adam/ontology/phase1_ontology.py, tests/curriculum/phase1_curriculum_test.py
=> Template for 'spin'

adam/curriculum_to_html.py
Closes https://github.com/isi-vista/adam/issues/218
=> Display Semantic Role Mappings of the Actions

adam/curriculum/phase1_curriculum.py, adam/ontology/phase1_ontology.py, tests/curriculum/phase1_curriculum_test.py
=> Template for push

adam/curriculum_to_html.py
=> Refine display of objects in semantic mapping

adam/curriculum_to_html.py
Closes https://github.com/isi-vista/adam/issues/281
=> Deduplicate Instances from HTML documents

adam/curriculum_to_html.py
=> Reduce pairs of size relations to one line

adam/curriculum/phase1_curriculum.py, adam/ontology/phase1_ontology.py, tests/curriculum/phase1_curriculum_test.py
=> throw curriculum

adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
Closes https://github.com/isi-vista/adam/issues/240
=> Objects should Contact the Ground unless otherwise stated

adam/curriculum_to_html.py
Closes https://github.com/isi-vista/adam/issues/273
=> Pretty Print Geons

adam/curriculum/phase1_curriculum.py, adam/curriculum_to_html.py, adam/language_specific/english/english_language_generator.py, adam/ontology/phase1_ontology.py, tests/curriculum/phase1_curriculum_test.py
closes https://github.com/isi-vista/adam/issues/200
=> Introduce come curriculum

adam/curriculum_to_html.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py
Closes https://github.com/isi-vista/adam/issues/300
=> Fix PartOf relationship in perception to match Ontology

adam/ontology/phase1_ontology.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Add prototypical colors to objects

adam/curriculum_to_html.py, parameters/curriculum_to_html.params
=> Html generator with sorting based on utterance length

adam/axes.py, adam/axis.py, adam/curriculum/phase1_curriculum.py, adam/curriculum_to_html.py, adam/language_specific/english/english_language_generator.py, adam/ontology/__init__.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/situation/templates/phase1_templates.py, tests/curriculum/phase1_curriculum_test.py, tests/language_specific/english/test_english_language_generator.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Template for behind/in-front

adam/curriculum_to_html.py
Closes https://github.com/isi-vista/adam/issues/259
=> Don't display 'other relations' if there are none.

adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Assign the same color to sub-objects of the same type

adam/curriculum/phase1_curriculum.py
=> Remove intransitives template

adam/curriculum_to_html.py
=> HTML dumps link back to indices

adam/curriculum_to_html.py
=> 260 correct list nesting for actions heading

adam/curriculum_to_html.py
=> Adjust partOf nesting

adam/experiment/__init__.py, adam/experiment/observer.py, adam/language_specific/english/english_language_generator.py, adam/learner.py, adam/learner/__init__.py, adam/learner/subset.py, tests/learner/learner_test.py
=> Subset learning algorithm

adam/curriculum_to_html.py
=> Remove duplicate instance name from title

adam/axis.py, adam/situation/__init__.py
=> Remove object and axis ids

adam/language_specific/english/english_language_generator.py, tests/language_specific/english/test_english_language_generator.py
=> Only pluralize objects if only object type in situation

adam/curriculum/phase1_curriculum.py, adam/curriculum/pursuit_curriculum.py, adam/situation/templates/phase1_templates.py, tests/curriculum/phase1_curriculum_test.py, tests/curriculum/pursuit_curriculum_test.py
=> Pursuit object recognition curriculum + with noise

adam/curriculum/pursuit_curriculum.py, adam/curriculum_to_html.py, parameters/curriculum_to_html.params, parameters/curriculum_to_html.sorted-by-utterance-length.params, parameters/html/curriculum_to_html.params, parameters/html/curriculum_to_html.phase1.params, parameters/html/curriculum_to_html.prepositions.params, parameters/html/curriculum_to_html.pursuit.params, parameters/html/curriculum_to_html.sorted-by-utterance-length.params
Closes https://github.com/isi-vista/adam/issues/395
The following zip can be used to verify the links are now relative.
[html.zip](https://github.com/isi-vista/adam/files/3764688/html.zip)
=> 395 index link fix

README.md
=> Add suggested reading to readme

adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> 365 centralize handling of colors

adam/axis.py, adam/curriculum_to_html.py
=> Add curriculum name to HTML dump

adam/learner/subset.py, adam/perception/_matcher.py, adam/perception/perception_graph.py, adam/utils/networkx_utils.py, benchmarks/test_benchmark_matching.py, tests/learner/learner_test.py, tests/perception/perception_graph_test.py, tests/utils/test_networkx_utils.py
=> Graph match renderer for debugging purposes

adam/curriculum/preposition_curriculum.py
=> Makes the learner the addressee rather than DAD in Preposition Curriculum

adam/curriculum/preposition_curriculum.py
=> Remove hollow objects from Preposition curricula except where needed

adam/curriculum/preposition_curriculum.py, adam/situation/templates/phase1_templates.py
=> Introduce Gaze to Preposition Curriculum 

adam/curriculum/preposition_curriculum.py, adam/ontology/phase1_ontology.py, adam/relation.py, tests/learner/preposition_learner_test.py
Closes #448 and incidentally implements a solution to issue #366 this issue will still need to have the already designed curriculum audited to implement the changes.
=> Introduce both DISTAL and PROXIMAL to Prepositions which distance is not a defining feature

adam/perception/perception_graph.py
=> Add axis information to perception graph

adam/situation/high_level_semantics_situation.py, tests/situation/high_level_semantics_situation.py
=> Make sure regions can't be gazed at in a situation by default

adam/curriculum/phase1_curriculum.py
=> Review phase1 curriculum to implement DSL functions where applicable

adam/curriculum_to_html.py
=> Explain colors in paragraph text & add 'color=' to display

adam/curriculum_to_html.py
=> Refine the display of Axis Information so it's clearer to understand

adam/axes.py, adam/curriculum_to_html.py
=> Add index to situation objects in HTML dumps

adam/curriculum_to_html.py
=> Don't display properties of properties for object perceptions

adam/curriculum/m6_curriculum.py, adam/curriculum_to_html.py
=> Curriculum for M6 milestone

adam/learner/preposition_subset.py, adam/learner/subset.py, adam/perception/_matcher.py, adam/perception/perception_graph.py, adam/utils/networkx_utils.py, tests/perception/perception_graph_test.py
Closes #461
Closes #479 
Closes #480 
Closes #481
=> Pattern relaxation

adam/curriculum/pursuit_curriculum.py, adam/learner/__init__.py, adam/learner/pursuit.py, adam/learner/subset.py, adam/perception/perception_graph.py, tests/learner/learner_test.py
=> Pursuit algorithm for object learning

adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py
=> Mark object size relative to learner as a property.

adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> implement grounding of unsupported objects

tests/perception/perception_graph_test.py
=> correcting syntactic/semantic feasibility tests

adam/experiment/log_experiment.py, adam/experiment/observer.py, tests/experiment_test.py
Added prediction accuracy counter in html output (also available to be used in tests) References https://github.com/isi-vista/adam/issues/568
=> Log prediction accuracy during learning / testing

adam/language_specific/english/english_language_generator.py, tests/language_specific/english/test_english_language_generator.py
=> Add regions as goals for english_language_generator.py

adam/curriculum/phase1_curriculum.py, adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/curriculum_to_html.py, parameters/html/curriculum_to_html.dynamic-prepositions.params, tests/curriculum/verbs_with_dynamic_prepositions_curriculum_test.py
=> Add push templates with dynamic prepositions

adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, tests/curriculum/verbs_with_dynamic_prepositions_curriculum_test.py
=> Add "go" with prepositions

adam/situation/templates/phase1_templates.py, tests/situation/templates/phase1_template_test.py
=> Allow SituationTemplates to set all relation fields

adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/language_specific/english/english_language_generator.py, adam/language_specific/english/english_syntax.py, tests/curriculum/verbs_with_dynamic_prepositions_curriculum_test.py, tests/language_specific/english/test_english_language_generator.py
Includes "sit (down) in"
Closes #284 
Closes #551
=> Curriculum for "sit down"

adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/curriculum_to_html.py, parameters/html/curriculum_to_html.dynamic-prepositions.params, tests/curriculum/verbs_with_dynamic_prepositions_curriculum_test.py
=> Add roll with prepositions to curriculum

adam/perception/perception_graph.py, requirements.txt, tests/perception/perception_graph_test.py
=> Translation of perception of dynamic situations to perception graphs

adam/curriculum/phase1_curriculum.py, adam/language_specific/english/english_language_generator.py, adam/situation/templates/phase1_templates.py
=> Come down Template & Curriculum Implementation

adam/curriculum/curriculum_utils.py, adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, tests/curriculum/verbs_with_dynamic_prepositions_curriculum_test.py
=> 555 put curriculum with new prepositions

adam/visualization/make_scenes.py, adam/visualization/positioning.py, tests/visualization/positioning_test.py
Specifically: 
- Scenes involving GO actions
Limitations:
- Implementation needed in positioning system for distance=in (e.g. "the dog goes in the car")
- Only this specific combination of action + arguments is handled so far.
=> Use of Action description to fix objects in place during positioning (proof of concept)

adam/experiment/log_experiment.py, adam/learner/object_recognizer.py, adam/ontology/phase1_ontology.py, adam/perception/perception_graph.py, tests/learner/__init__.py, tests/learner/subset_preposition_learner_test.py, tests/learner/subset_verb_learner_test.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Create PerceptionGraphPatterns from OntologyNodes

adam/curriculum/phase1_curriculum.py, adam/language_specific/english/english_language_generator.py, tests/learner/subset_attribute_learner_test.py
=> Use Subset Attribute Learner to learn 'my' and 'your'

adam/visualization/make_scenes.py, adam/visualization/positioning.py
Closes #652 
A further elaboration of "visualizing paths" #621
=> Middle-frame (visualize 'relations holding at some point')

adam/learner/object_recognizer.py, adam/perception/perception_graph.py
See https://github.com/isi-vista/adam/issues/666 for discussion
=> Hack to work around our lack of digraphs.

adam/perception/perception_graph.py
Closes #674
Addresses part of #593  (paths, but not enduring relations)
=> Translate Paths to perception graphs

adam/curriculum/phase1_curriculum.py, adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/ontology/phase1_ontology.py, adam/situation/templates/phase1_situation_templates.py
Closes #569  by deciding that "a dog goes" isn't natural English.
Closes #676
=> Don't permit bare "go" in language generation

adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/language_specific/english/english_language_generator.py, adam/ontology/phase1_ontology.py
Adds the situation from #318 but doesn't fully implement manipulator bindings
=> X throws Y to Z template

adam/visualization/make_scenes.py, adam/visualization/panda3d_interface.py, adam/visualization/positioning.py, adam/visualization/render_curriculum.py, adam/visualization/utils.py, parameters/render_curriculum.params
PR for the standalone version of writing out .JPGs for each scene (from phase1 curricula)
=> automated renderer

adam/curriculum/phase1_curriculum.py, adam/perception/perception_graph.py, tests/learner/subset_verb_learner_test.py
Improved #672 to only need to disable "fly under"
=> Re-introduce "fly"

adam/learner/perception_graph_template.py, adam/ontology/phase1_ontology.py, adam/perception/perception_graph.py, tests/language_specific/english/test_english_language_generator.py
Closes #698 
Closes #593
Closes #697
Closes #695
=> Translate "during" relations of actions to perception graphs

adam/curriculum/phase1_curriculum.py, adam/language/dependency/universal_dependencies.py, adam/language_specific/english/english_language_generator.py, adam/language_specific/english/english_syntax.py, tests/curriculum/phase1_curriculum_test.py
=> x-is-y-syntax

adam/learner/object_recognizer.py, adam/perception/perception_graph.py, tests/learner/pursuit_preposition_learner_test.py, tests/learner/subset_preposition_learner_test.py
=> 694 keep internal properties

adam/curriculum/phase1_curriculum.py, adam/ontology/phase1_ontology.py, adam/perception/perception_graph.py
=> Restore X throws Y to Z to the curriculum

adam/curriculum/phase1_curriculum.py, adam/learner/learner_utils.py, adam/learner/perception_graph_template.py
=> Properly learn my/your

adam/curriculum/phase1_curriculum.py
=> Display all possible colors for objects when learning them

adam/experiment/observer.py, adam/visualization/render_curriculum.py, parameters/visualization/m9_attributes.params, parameters/visualization/m9_debug.params, parameters/visualization/m9_events.params, parameters/visualization/m9_objects.params, parameters/visualization/m9_relations.params, parameters/visualization/render_curriculum.params, parameters/visualization/render_m9.params
=> fixed output paths for running entire m9 experiment

adam/experiment/observer.py, adam/visualization/make_scenes.py, adam/visualization/positioning.py, adam/visualization/render_curriculum.py
Closes #688 
nans were happening in interpolated (frame 2/3) scenes that shouldn't have been being generated (in pushing scenes).
=> Eliminated erroneous scene where object positions were getting set to nan

adam/curriculum_to_html.py, adam/visualization/make_scenes.py
=> Remove deprecated optional function calls

adam/curriculum/attribute_constraining_action_curriculum.py, adam/curriculum/phase1_curriculum.py, adam/curriculum_to_html.py, parameters/html/curriculum_to_html.essen_fressen_distinction.params, tests/curriculum/attribute_constraining_action_curriculum_test.py, tests/learner/subset_verb_learner_test.py
=> Animal and human eat as specific curriculum for attributes which constrain actions

adam/curriculum_to_html.py
=> Refine information in Curriculum to HTML dumps

adam/language_specific/__init__.py, adam/language_specific/chinese/chinese_phase_1_lexicon.py, adam/language_specific/chinese/chinese_syntax.py, adam/language_specific/english/english_language_generator.py, adam/language_specific/english/english_phase_1_lexicon.py, adam/language_specific/english/english_syntax.py
#778: creates language_specific/chinese directory with Chinese lexicon and dummy syntax file
=> 778 chinese lexicon

adam/curriculum/phase1_curriculum.py, adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/language_specific/english/english_language_generator.py, tests/curriculum/verbs_with_dynamic_prepositions_curriculum_test.py
=> Add temporally relevant dynamic prepositions.

adam/language_specific/chinese/chinese_language_generator.py, adam/language_specific/chinese/chinese_phase_1_lexicon.py, adam/language_specific/chinese/chinese_syntax.py, tests/language_specific/chinese/test_chinese_language_generator.py, tests/language_specific/chinese/test_chinese_syntax.py
Initial implementation to generate NP's with modifiers, possessives, and nominal modifiers.
=> Chinese language generator basic

adam/language_specific/english/english_language_generator.py, adam/situation/__init__.py, tests/language_specific/english/test_english_language_generator.py
=> Increase test coverage of english language generator

adam/curriculum/curriculum_utils.py, adam/curriculum/imprecise_descriptions_curriculum.py, adam/curriculum/phase1_curriculum.py, adam/curriculum_to_html.py, adam/language_specific/english/english_language_generator.py, adam/ontology/during.py, adam/ontology/phase1_ontology.py, adam/ontology/phase1_spatial_relations.py, parameters/html/curriculum_to_html.imprecise-temporal, tests/curriculum/imprecise_descriptions_curriculum_test.py, tests/language_specific/english/test_english_language_generator.py
=> Add Imprecise Temporal Descriptions Curriculum

adam/learner/perception_graph_template.py, adam/learner/subset.py, adam/perception/perception_graph.py, tests/perception/perception_graph_test.py
=> Fix bad hypothesis intersections for verb subset learner

adam/curriculum/curriculum_utils.py, adam/learner/subset.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Translate subobject properties

adam/learner/object_recognizer.py, adam/learner/template_learner.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, tests/learner/object_learner_test.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Hierarchical object recognition

adam/curriculum/curriculum_utils.py, adam/learner/object_recognizer.py, tests/learner/subset_verb_learner_test.py
=> Fix subset verb learner tests

adam/curriculum/attribute_constraining_action_curriculum.py, adam/curriculum/imprecise_descriptions_curriculum.py, adam/curriculum/m6_curriculum.py, adam/curriculum/phase1_curriculum.py, adam/curriculum/phase2_curriculum.py, adam/curriculum/preposition_curriculum.py, adam/curriculum/pursuit_curriculum.py, adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/curriculum_to_html.py, adam/language_specific/chinese/chinese_language_generator.py, adam/situation/templates/phase1_situation_templates.py, parameters/html/curriculum_to_html.dynamic-prepositions.chinese.params, parameters/html/curriculum_to_html.essen_fressen_distinction.chinese.params, parameters/html/curriculum_to_html.imprecise-size.chinese.params, parameters/html/curriculum_to_html.imprecise-temporal.chinese.params, parameters/html/curriculum_to_html.m8.chinese.params, parameters/html/curriculum_to_html.phase1.chinese.params, parameters/html/curriculum_to_html.prepositions.chinese.params, parameters/html/curriculum_to_html.pursuit.chinese.params, parameters/html/curriculum_to_html.sorted-by-utterance-length.chinese.params, tests/curriculum/imprecise_descriptions_curriculum_test.py, tests/curriculum/phase1_curriculum_test.py, tests/curriculum_to_html_test.py, tests/language_specific/chinese/test_chinese_language_generator.py
closes #856 
closes #855 
Issues discovered while going through curricula: #860, #859, #858
=> Chinese HTML curriculum dump

adam/curriculum/imprecise_descriptions_curriculum.py, adam/curriculum/phase1_curriculum.py, tests/curriculum/phase1_curriculum_test.py
=> Push shove adverbial path modifier

adam/language_specific/english/english_language_generator.py, tests/language_specific/english/test_english_language_generator.py
=> Count only salient objects

adam/learner/attributes.py, adam/learner/learner_utils.py, adam/learner/relations.py, adam/learner/verbs.py
=> Verify that all templates need to learn from the entire utterance.

adam/curriculum/phase1_curriculum.py, adam/language_specific/chinese/chinese_language_generator.py, adam/learner/attributes.py, adam/learner/integrated_learner.py, adam/learner/objects.py, adam/learner/prepositions.py, adam/learner/surface_templates.py, adam/learner/template_learner.py, adam/learner/verbs.py, tests/curriculum/phase1_curriculum_test.py, tests/learner/pursuit_preposition_learner_test.py, tests/learner/subset_attribute_learner_test.py, tests/learner/subset_preposition_learner_test.py, tests/learner/subset_verb_learner_test.py
=> Debug updated learner for Chinese 

adam/learner/__init__.py, adam/learner/learner_utils.py, adam/learner/relations.py, adam/learner/verbs.py, tests/learner/subset_preposition_learner_test.py
=> Updated preposition learner

adam/experiment/log_experiment.py, adam/learner/learner_utils.py, adam/learner/verbs.py
=> FixedStrings no longer include recognized concepts in them

adam/experiment/log_experiment.py, adam/experiment/run_object_restrictions.py, adam/language_specific/english/__init__.py, adam/learner/__init__.py, adam/ontology/phase1_ontology.py, adam/perception/perception_graph.py, parameters/experiments/object_restrictions.params, requirements.txt
=> 809 learn object restrictions

adam/learner/perception_graph_template.py
=> close #888

adam/learner/object_recognizer.py, adam/ontology/phase1_ontology.py, adam/perception/_matcher.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/perception/perception_graph.py, tests/perception/perception_graph_test.py
=> Use monomorphism mode for perception graph pattern matching

tests/learner/__init__.py, tests/learner/pursuit_preposition_learner_test.py, tests/learner/subset_attribute_learner_test.py, tests/learner/subset_preposition_learner_test.py, tests/learner/subset_verb_learner_test.py, tests/learner/test_integrated_learner.py, tests/learner/test_object_recognizer.py
=> Tests: Use one object recognizer copy for each language mode

adam/learner/objects.py, adam/learner/pursuit.py, adam/learner/subset.py, tests/learner/object_learner_test.py
=> New Pursuit Learner

adam/perception/perception_graph.py
Closes #910 Closes #745 
Waiting on #890
=> Add Spatial Path Properties

.travis.yml, Makefile, adam/curriculum_to_html.py, requirements.txt, requirements_pypy.txt
=> Use PyPy to execute tests on Travis

adam/perception/_matcher.py, tests/learner/object_learner_test.py
=> Remove unnecessary usage of immutableset

adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py, adam/experiment/log_experiment.py, adam/language_specific/english/english_language_generator.py, adam/situation/high_level_semantics_situation.py
=> Update curriculum to be able to learn dynamic prepositions

README.md, adam/curriculum_to_html.py, parameters/html/curriculum_to_html.dynamic-prepositions.chinese.params, parameters/html/curriculum_to_html.dynamic-prepositions.params, parameters/html/curriculum_to_html.essen_fressen_distinction.chinese.params, parameters/html/curriculum_to_html.essen_fressen_distinction.params, parameters/html/curriculum_to_html.imprecise-size.chinese.params, parameters/html/curriculum_to_html.imprecise-size.params, parameters/html/curriculum_to_html.imprecise-temporal.chinese.params, parameters/html/curriculum_to_html.imprecise-temporal.params, parameters/html/curriculum_to_html.m8.chinese.params, parameters/html/curriculum_to_html.m8.params, parameters/html/curriculum_to_html.phase1.chinese.params, parameters/html/curriculum_to_html.phase1.params, parameters/html/curriculum_to_html.prepositions.chinese.params, parameters/html/curriculum_to_html.prepositions.params, parameters/html/curriculum_to_html.pursuit.chinese.params, parameters/html/curriculum_to_html.pursuit.params, parameters/html/curriculum_to_html.sorted-by-utterance-length.chinese.params, parameters/html/curriculum_to_html.sorted-by-utterance-length.params
=> Chinese params

adam/experiment/log_experiment.py, adam/learner/object_recognizer.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/perception/perception_graph.py, tests/learner/__init__.py, tests/perception/perception_graph_test.py
=> Control of how reliably gaze is perceived

adam/perception/perception_graph.py
=> Remove extra graph copying

adam/experiment/log_experiment.py, adam/learner/template_learner.py, adam/perception/perception_graph.py
=> Integrated pursuit object learner 

adam/curriculum/phase1_curriculum.py, adam/curriculum/phase2_curriculum.py, adam/experiment/__init__.py, adam/experiment/experiment_utils.py, adam/experiment/log_experiment.py, adam/experiment/observer.py, adam/language_specific/english/english_language_generator.py, adam/learner/alignments.py, adam/learner/attributes.py, adam/learner/functional_learner.py, adam/learner/integrated_learner.py, adam/learner/learner_utils.py, adam/learner/object_recognizer.py, adam/learner/objects.py, adam/learner/relations.py, adam/learner/template_learner.py, adam/learner/verbs.py, adam/ontology/phase2_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, adam/perception/perception_graph.py, adam/semantics.py, parameters/experiments/m13/m13.debug.params, tests/learner/functional_learner_test.py, tests/learner/object_learner_test.py, tests/learner/subset_attribute_learner_test.py, tests/learner/subset_preposition_learner_test.py, tests/learner/subset_verb_learner_test.py, tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
=> Functional Learner

adam/experiment/__init__.py
=> serialize learner state at the end

adam/pickle.py, tests/learner/subset_verb_learner_test.py, tests/pickle_test.py
This resolves the pickling problems discussed on #958.
=> Add AdamPickler/Unpickler which handle persistence of shared world items and GROUND_PERCEPTION

adam/learner/__init__.py, adam/learner/learner_utils.py, adam/learner/objects.py, adam/learner/propose_but_verify.py, adam/learner/pursuit.py, adam/learner/subset.py, adam/learner/template_learner.py, tests/learner/object_learner_test.py
=> Add Propose But Verify learner to Objects & simple unit test.

adam/curriculum/__init__.py, adam/curriculum/phase2_curriculum.py, adam/experiment/experiment_utils.py, adam/experiment/log_experiment.py, adam/experiment/observer.py, adam/language/__init__.py, adam/language/dependency/__init__.py, tests/curriculum/phase2_curriculum_test.py
Closes #971 
Closes #970 (For Objects)
=> Implement Precision and Recall observer for experiment logging

adam/experiment/__init__.py, adam/experiment/gaze_ablation.py, parameters/experiments/gaze_ablation_runner.debug.params, parameters/experiments/gaze_ablation_runner.params
The workflow itself seems to function.
However, about 20 of the jobs reach a point where they hang and are eventually terminated. They each hang for at least 40 minutes. There's no obvious pattern in the pursuit parameters that hang. They seem to be hanging during pattern matching or relaxation. Sometimes the last messages before the hang are "blocking match against a non-subobject portion..." and sometimes they're "Relaxation: Last failed pattern node is..."/"Nodes to delete directly: ..."
Depends on the experiment script changes from #957.
=> Run gaze ablation experiments using Pegasus

README.md
=> Document required root parameters for Pegasus workflows

adam/curriculum/__init__.py, adam/experiment/README.md, adam/experiment/__init__.py, adam/experiment/experiment_utils.py, adam/experiment/log_experiment.py, adam/experiment/observer.py, adam/experiment/run_object_language_ablation_experiment.py, parameters/experiments/m15/object_learners_experiments.params, requirements_pegasus.txt
=> Object Language Ablation Experiments

adam/experiment/curriculum_repository.py, adam/experiment/generate_curriculum.py, adam/experiment/log_experiment.py, adam/learner/language_mode.py, parameters/experiments/m13/curriculum_generation_debug.params, parameters/experiments/m13/load_object_curriculum_pickle.params
Should allow for parallel curriculum generation (#958), although it does not implement any workflow to do that.
=> Curriculum generation

adam/curriculum/curriculum_utils.py, adam/curriculum/phase2_curriculum.py, adam/curriculum/preposition_curriculum.py, adam/curriculum_to_html.py, adam/language/language_utils.py, adam/language_specific/english/english_integrated_experiment_lexicon.py, adam/language_specific/english/english_language_generator.py, adam/ontology/integrated_learner_experiement_ontology.py, adam/ontology/phase1_ontology.py, adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py, parameters/html/curriculum_to_html.integrated_experiment.params
=> Pursuit Integrated Experiment Curriculum

adam/experiment/log_experiment.py, adam/experiment/observer.py, adam/learner/__init__.py, adam/learner/attributes.py, adam/learner/integrated_learner.py, adam/learner/object_recognizer.py, adam/learner/objects.py, adam/learner/pursuit.py, adam/learner/surface_templates.py, adam/perception/perception_graph.py, parameters/experiments/m18/integrated_pursuit_attribute_only.params, parameters/experiments/m18/m18.params, tests/learner/pursuit_attribute_learner_test.py
=> Pursuit attribute learner

adam/learner/objects.py, adam/learner/plurals.py, adam/learner/propose_but_verify.py, adam/learner/pursuit.py, adam/learner/relations.py, adam/learner/subset.py, adam/learner/template_learner.py, adam/semantics.py, tests/learner/pursuit_preposition_learner_test.py
=> Add Pursuit Relations Learner

adam/experiment/README.md, adam/experiment/experiment_utils.py, adam/learner/cross_situational_learner.py, adam/learner/objects.py, adam/learner/propose_but_verify.py, adam/learner/template_learner.py, tests/learner/object_learner_test.py
=> Implement Cross Situation Learner as Template Learner

adam/experiment/observer.py, adam/learner/cross_situational_learner.py, adam/learner/template_learner.py, parameters/experiments/m13/pursuit_with_noisy_gaze.params
Updates to the accuracy/precision/recall logging meant the old gaze param files weren't compatible, so I updated them.
=> Pursuit gaze debugging

requirements_pegasus.txt
=> Fix Pegasus requirements

adam/curriculum/curriculum_utils.py, adam/curriculum/phase2_curriculum.py, adam/curriculum/preposition_curriculum.py, adam/curriculum_to_html.py, adam/experiment/README.md, adam/experiment/__init__.py, adam/experiment/curriculum_repository.py, adam/experiment/experiment_utils.py, adam/experiment/log_experiment.py, adam/experiment/make_integrated_experiment.py, adam/learner/integrated_learner.py, adam/learner/learner_utils.py, adam/learner/objects.py, adam/learner/surface_templates.py, adam/perception/_matcher.py, parameters/experiments/m18/integrated_experiment.params, parameters/experiments/m18/integrated_experiment_demo.params, parameters/html/curriculum_to_html.integrated_experiment_test.params, tests/learner/pursuit_preposition_learner_test.py, tests/learner/subset_preposition_learner_test.py
=> Integrated Experiment Revisions & Bug fixes

docs/index.rst
=> Update documentation to reflect status of entry point and of demo

README.md
=> Updated ReadME to have npm install instructions

adam/experiment/curriculum_repository.py, adam/experiment/log_experiment.py, adam/experiment/run_p3.sh, adam/experiment/run_p3_learner.py, adam/perception/__init__.py, parameters/experiments/p3/p3.params
=> P3 learner entry point

adam/experiment/experiment_data_loader.py, adam/experiment/p3_sample_output/learners/integrated_subset/experiments/objects_one/test_curriculums/object_test_curriculum_one/situation_1/post_decode.yaml
sample learner output directory included. #1029
=> Data Loader for UI

adam/perception/perception_graph.py, adam/perception/perception_graph_nodes.py, adam/perception/perception_graph_predicates.py
Needed for perception features as discussed in #1022
=> Add new nodes and predicates for perception graphs

adam/experiment/observer.py
Works on #1045 
This is not a complete implementation of the desired output of the P3 Observer as the information to extract features correlated with object clusters in the scene is not currently available to the observer. I believe the simplest change at this point will be to retrieve this information from the perceptual representation created from the visual sensors & processing output. Once this format has been established I'll resume extracting the feature information for this observer.
Going to consider the expansion of this observer a combined experiment PR after all individual portions of the changes have been merged.
=> Initial P3 Observer

angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.css, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.html, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.ts, angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.html, angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.ts
Updated parsing method to handle the case where no sub-objects are present for an object
=> updated parsing method of post-decode file

adam/flask_backend/app.py, angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.ts
Fixed my typescript errors from running precommit on #1080 and #1081
=> Fix Angular TypeScript typing errors

angular-viewer/adam-angular-demo/src/app/classes/features.ts, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.html, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.ts
I added a boolean attribute `isColor` to the property object which uses regex to determine whether the color swatch should be displayed in HTML on the corresponding line. The color is displayed on a square whose font color matches the property color.
=> If object has a color property, display a swatch of that color in the properties list #1088

adam/curriculum/curriculum_from_files.py, adam/math_3d.py, adam/perception/__init__.py, adam/perception/perception_graph.py, adam/perception/perception_graph_nodes.py, adam/perception/perception_graph_predicates.py, adam/perception/visual_perception.py, adam/situation/phase_3_situations.py
Add ability to read and store multi-frame scenes in ADAM's phase 3 curriculum.
=> Add multi-frame VisualPerceptionRepresentation

.travis.yml, README.md, adam/curriculum/curriculum_from_files.py, adam/experiment/observer.py, adam/ontology/phase3_ontology.py, adam/perception/perception_graph_predicates.py, angular-viewer/adam-angular-demo/src/app/components/header/header.component.html, parameters/experiments/p3/m5_contrastive_object_learning.params, parameters/experiments/p3/m5_objects.params, parameters/experiments/p3/m5_objects_v0.params, parameters/experiments/p3/m5_objects_v0_subset.params, parameters/experiments/p3/m5_objects_v0_with_mugs_subset.params, requirements.txt, requirements_lock.txt, scripts/reorganize_curriculum.py, tests/continuous_test.py
Precommit passes (other than mypy complaining about no pyyaml types). Tests pass. Git history should be relatively clean.
=> M5 object learner experiment

adam/experiment/run_contrastive_learning_experiment.py, adam/learner/__init__.py, adam/learner/contrastive_learner.py, adam/learner/subset.py, parameters/experiments/p3/m6_contrastive_object_learning.params, parameters/experiments/p3/m6_contrastive_object_learning_without_logging.params
Precommit and tests pass. I mainly just added a new function for retrieving a list of concepts, a function for retrieving multiple hypotheses from a learner, and updated the preexisting functions to work around multiple hypotheses rather than a single one.
Closes #1138
=> 1138 contrastive no primary template

angular-viewer/adam-angular-demo/src/app/classes/affordances.spec.ts, angular-viewer/adam-angular-demo/src/app/classes/affordances.ts, angular-viewer/adam-angular-demo/src/app/classes/linguistic-output.ts, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.css, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.html, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.ts, angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.ts
Closes #1145
Since #1141 handles adding affordances to the decode, I've added everything required from the angular side to display affordances in the front end.
=> 1145 display for affordances

adam/learner/affordances.py, adam/learner/integrated_learner.py, adam/learner/object_recognizer.py, adam/learner/perception_graph_template.py, scripts/organize_action_curriculum.py
Adds a new affordance curriculum type from the m5 actions curriculum & fixes a few bugs from the observational affordance learner.
=> Bug fixes for observational affordance learner.

adam/flask_backend/app.py, adam/flask_backend/utils.py, adam/paths.py, angular-viewer/adam-angular-demo/angular.json, angular-viewer/adam-angular-demo/src/app/components/image-output/image-output.component.html, angular-viewer/adam-angular-demo/src/app/components/image-output/image-output.component.ts, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.css, angular-viewer/adam-angular-demo/src/app/components/object-results/object-results.component.html, angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.css, angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.html, angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.ts
Closes the live image display portion of #1159 
There are 2 major changes present in this update:
- Add functionality to send image files from directory exterior to angular working directory:
- Rather than just providing image paths, this encodes the image in a base64 string in the flask back end and sends the embedded image object in response to an HTTP GET request. 
- Then the image is decoded and displayed in the front end.
- Also means assets do not need to be cloned/duplicated into the Angular working directory at build time
- Add polling service to display changes in back end
- The app stores a trace of the available data when the app is initiated
- Every 10 seconds, the app sends a GET request to the back end to see if any new data is present (can be manually adjusted)
- Once the …
=> Frontend live updates

adam/curriculum/curriculum_from_files.py, adam/experiment/live_demo.py, adam/flask_backend/app.py, adam/paths.py, adam_preprocessing/shape_stroke_extraction.py, adam_preprocessing/shape_stroke_graph_inference.py, adam_preprocessing/utils.py, angular-viewer/adam-angular-demo/src/environments/environment.ts, requirements.txt, requirements_lock.txt
Currently a WIP dive demo script. Preprocessing integration is still needed before this can be tested fully.
=> Add Live Demo Script

adam_preprocessing/shape_stroke_graph_inference.py
=> Preprocessing fixes

README.md, adam_preprocessing/README.md
Closes #1172. Also addresses the other README issues we discussed last team meeting.
=> Readme fixes

adam_preprocessing/utils.py
=> Fix stroke data loading bug where nodes_seen is not updated

adam_preprocessing/shape_stroke_graph_inference.py, adam_preprocessing/shape_stroke_graph_learner.py, adam_preprocessing/utils.py
This is still very messy and incomplete (I haven't touched the training script; the `num_objs` variable turned out to be unnecessary, will factor out soon) but I wanted to check in sooner rather than later that this is the desired change (of recognizing multiple objects in preprocessing) for later adding spatial relations to ADAM.
EDIT: This PR is now ready for review
=> Predict diverse objects in scenarios

adam/curriculum/curriculum_from_files.py
Will enable easier running of automated tests across curriculum developed for experimentation.
=> Remove Phase 3 valid curriculum name restriction

adam/experiment/run_pipeline.py, adam_preprocessing/color_refine_curriculum.py, parameters/experiments/p3/m6_color_refine_baseline_airsim.params, parameters/experiments/p3/m6_color_refine_baseline_stego.params, parameters/experiments/p3/m6_color_refine_merged_airsim.params, parameters/experiments/p3/m6_color_refine_merged_stego.params, parameters/experiments/p3/m6_color_refine_refined_airsim.params, parameters/experiments/p3/m6_color_refine_refined_stego.params, parameters/experiments/p3/m6_color_refine_refinedmerged_airsim.params, parameters/experiments/p3/m6_color_refine_refinedmerged_stego.params
These are the parameters and fixes/changes for the color refinement experiments over the M5 objects curriculum.
=> Color refine experiment

adam/perception/visual_perception.py
=> Move size numbers to ClusterPerception properties

adam_preprocessing/color_refine_curriculum.py
=> Fix bug where color refining doesn't change segmentation

adam_preprocessing/shape_stroke_extraction.py, adam_preprocessing/singlefile_stroke_extraction.py
=> Fix stroke merging logic bugs

adam_preprocessing/predict.sh, adam_preprocessing/shape_stroke_graph_inference.py, adam_preprocessing/shape_stroke_graph_learner.py, adam_preprocessing/utils.py
=> Calculate situation-level GNN test accuracy

adam_preprocessing/shape_stroke_extraction.py, adam_preprocessing/singlefile_stroke_extraction.py, scripts/generate_curriculum_from_images.py
Fixes #1205.
Having just requested review, I realize I need to duplicate these changes in `adam_preprocessing/single_file_extraction.py`. That said, I think it is far enough along in `shape_stroke_extraction.py` to make review worth it
=> Stop merging objects

slurm/adam.sh
Allow for maximum time on ephemeral for longer-running experiments
=> Increase max time for ADAM jobs on cluster
