- adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py
- adam/perception/perception_graph.py
- tests/learner/learner_test.py
- tests/perception/perception_graph_test.py
In this implementation we remove unwanted nodes from graphs created from schemas before creating patterns from those graphs (colors, property assertions, regions, ground, and learner) - it's worth double checking that's the intended behavior, and that we don't remove too much.
closes #407
> Generate perception patterns from perception graphs

- adam/curriculum/preposition_curriculum.py
closes #438 
Changes to the resulting curriculum can be viewed in the `preposition` curricula.
[CurriculaNov11_22_19.zip](https://github.com/isi-vista/adam/files/3881870/CurriculaNov11_22_19.zip)
> Introduce animate objects to training stages of preposition curriculum

- adam/visualization/__init__.py
- adam/visualization/make_scenes.py
- adam/visualization/panda3d_interface.py
- adam/visualization/positioning.py
- parameters/make_scenes.params
- requirements.txt
- tests/visualization/make_scenes_test.py
- tests/visualization/panda_interface_test.py
- tests/visualization/positioning_test.py
Closes #392 original issue was due to some of the 'people' in scenes not having any properties attached to their arms/legs/etc (no color, no animacy, etc), not due to any nesting issues.
The new method of traversing all objects in a scene to find objects with geons gets around the issue of some objects not having any properties.
At any rate, the goal with this PR is to come up with a nested representation for scene objects that are `partOf` others so that later on they can be positioned/oriented/scaled relative to their parent object.
> 392 nested geons

- adam/visualization/panda3d_interface.py
Closes #537 
Adds:
`from panda3d.core import Filename` 
and use that to:
`working_dir = Filename.fromOsSpecific(os.path.abspath((sys.path[0])))`
This creates a Path `(working_dir)` that Panda3d can read regardless of OS.
> "Added FilePath conversion to work on any OS"

- .coveragec
- .coveragerc
- adam/visualization/make_scenes.py
- adam/visualization/panda3d_interface.py
- adam/visualization/positioning.py
- adam/visualization/utils.py
Generally speaking, the visualization system has some strange execution paths that make it unsuitable for some of our CI tools -- i.e. Travis can't open up a graphics window to test those parts of the code)
> Ignore test coverage checks for Visualization source files

- adam/perception/perception_graph.py
…during pattern generalization -- m6 ran w/o raising it. Closes #512
> Restore disabled error message for patterns matching multiple connected components

- adam/language_specific/english/english_language_generator.py
- tests/language_specific/english/test_english_language_generator.py
Closes #605 
My attempt at this task:
I think this has to do with `HAS` being a `RELATION` and not an `ACTION` even though it is a verb. As such, the speaker is never recognized as the `NOMINAL_SUBJECT`, resulting in the default `ME` being used.
I added a special case in noun_for_object() in the english_language_generator:
This seems to fix it, and I don't see any obvious cases where it affects the other parts:
```
if IS_SPEAKER in _object.properties:
if syntactic_role_if_known == NOMINAL_SUBJECT:
noun_lexicon_entry = I
elif any(
relation
for relation in self.situation.always_relations
if (
relation.relation_type == HAS
and any(
property_ in relation.first_slot.properties
for property_ in [IS_SPEAKER]
)
and len(self.situation.actions) == 0
)
):
else:
noun_lexicon_entry = ME
```
NOTE: I …
> Translating subject (speaker) as "I" when using HAS

- adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py
- tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
This seemed like the simplest point to intervene in the process of creating an `ObjectPerception` to ensure that its `debug_handle` corresponds with the particular type of human involved. (Mom, Dad, Baby). 
For context, the visualization system relies on the debug_handle strings of `ObjectPerception`s (strictly speaking, not information given to any learner) in order do things that depend on the object's type such as loading the correct geometry for the object type, or scaling it according to its type, etc. In the case of people (see #603) `ObjectPerceptions` for particular sorts of people have their debug_handles set to their supertype: Person. 
I can add some explanatory comments before merging, but I wanted to check if this overall is in _bad idea_ territory.
> 603 scaling people

- adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py
- tests/perception/high_level_semantics_situation_to_developmental_primitive_perception_test.py
- Changed `_perceived_ground_relations()` to take a relations parameter
so that before and after relations can be included
- Moved to `_perceived_ground_relations()` call from
`_perceive_action()` to `_real_do()` as to include all relations
Tested fix:
Closes #596
> Corrected implicit ground relation to consider before and after action relations

- adam/visualization/make_scenes.py
- adam/visualization/positioning.py
- Positioned objects will resume from where they left off in a multi-part scene
- Current frame is displayed in scene title
Still needs:
- ~code cleanup in `positioning.py` - ways of creating the PositioningModel / AxisAlignedBoundingBoxes have lots of duplication~
- ~test fixes~
Future idea behind this PR:
- Might be useful to fix the position of particular objects in a continuing frame
(for example: a goal object should potentially remain in place, while the agent moves toward it)
> Frame aware scenes

- adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py
As referenced: https://github.com/isi-vista/adam/issues/569#issuecomment-600213478 disabling "go to" for phase 1 verb curriculum as it's functionally identical to "go (near)"
> Disable "go to" for phase 1

- adam/curriculum/phase1_curriculum.py
Addresses part of #639 by allowing the Learner to identify "me" and "you" but not allowing a way to instantiate a pattern for "me/I" or "you" in the ObjectRecognizer if not using the ObjectLearner
> Introduce "me" and "you" to Every Object Curriculum

- adam/curriculum/phase1_curriculum.py
- adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py
- adam/experiment/log_experiment.py
- adam/ontology/phase1_ontology.py
- adam/perception/high_level_semantics_situation_to_developmental_primitive_perception.py
Fixes the following: 
- keep rolling object on rolling surface
- make sure that the thrown object isn't necessarily always on the ground before and after
- make sure that a flying this isn't on the ground 
- add distinguishing between "jump" and "jump up" 
- add distinguishing between "run" and "run down" and "walk" and "walk down"
- the cup when drinking should be the same size throughout the action 
- learn both "over" and "under" (TODO: currently both of these have both objects on the ground #929 )
> Fix miscellaneous semantics 

- adam/experiment/__init__.py
- adam/experiment/log_experiment.py
- adam/experiment/observer.py
- adam/learner/__init__.py
- adam/learner/functional_learner.py
- adam/learner/integrated_learner.py
- adam/learner/objects.py
- adam/learner/template_learner.py
- parameters/experiments/m13/m13.debug.params
- parameters/experiments/m13/pursuit_with_noisy_gaze.params
This fixes the issue that our HTML file was beginning indexing at -1; it and the logging now start at 0 
It also adds an optional way of logging accuracy at each iteration of the experiment to create graphs like the ones shown [here](https://www.dropbox.com/scl/fi/n1bgnqr3v4tj35lz0mzw2/Gaze-Ablation-in-Pursuit-Object-Learning.paper?dl=0&rlkey=rijevp5ei2y5orjwodednnr2g).
> Fix indexing and add accuracy logging 

- adam/curriculum/phase1_curriculum.py
- adam/curriculum/phase2_curriculum.py
- adam/curriculum/verbs_with_dynamic_prepositions_curriculum.py
- adam/language_specific/chinese/chinese_language_generator.py
- adam/learner/alignments.py
- adam/learner/surface_templates.py
- adam/learner/template_learner.py
- tests/language_specific/chinese/test_chinese_language_generator.py
can run `run_m13` without encountering an error in English and Chinese now with `m13.params`
For `log_experiment` with `m13_complete`, our issue in English is "throw", since we have two possible "throw-to" templates; one indicates goal and one indicates recipient. For English, we express both with "to" but in Chinese we can distinguish since there is a different coverb indicating person goal ("gei")
> Debugging to run entire M13 without crashing

- adam/curriculum/phase2_curriculum.py
- adam/curriculum_to_html.py
- parameters/html/curriculum_to_html.chinese_classifiers.params
So that we can run it in Chinese separate from the rest of the Phase 2 curriculum (which was generated in English), as we probably want to.
> Create separate Chinese classifier curriculum in curriculum_to_html

- angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.html
- angular-viewer/adam-angular-demo/src/app/components/selector-parent/selector-parent.component.ts
Reset functionality sets the values of dropdowns to "None" instead of initial value. Will need further polishing to rectify this, problem is caused by the use of NgModel.
> Add reset button

- .travis.yml
- angular-viewer/adam-angular-demo/Makefile
Closes #1059 
Changes to the .travel.yml configuration file so that the Angular UI app runs `make check` as part of CI automatically. This step is placed after the python recommit checks but before the python tests based on speed to failure.
> Run travis CI on Angular UI

- adam/curriculum/curriculum_to_yaml.py
- adam/curriculum/phase3_curriculum.py
- adam/language_specific/english/english_phase_3_lexicon.py
- adam/ontology/phase1_ontology.py
- adam/ontology/phase3_ontology.py
- tests/curriculum/phase3_curriculum_test.py
This PR was used to generate the curriculum uploaded in #1063 
For easier use in other sections of code I've moved from using `ABC` to a `Protocol` -- A protocol makes more sense for the functionality I'm using it for to ensure that I can call any curriculum builder function with the same set of arguments and get an expected curriculum output. Not all curriculum builders will use all the arguments, but this is the minimum set used by all of them.
> Update P3 curriculum for M4 goals

- adam/experiment/observer.py
- adam/learner/learner_utils.py
- adam/learner/object_recognizer.py
- adam/perception/visual_perception.py
- adam/semantics.py
Closes #1104 by tracking an original node ID via the detected semantic_node when applicable.
> Update ID tracking to use ID from graph nodes if one exists

- adam/perception/perception_graph_nodes.py
- adam/perception/perception_graph_predicates.py
- tests/perception/perception_graph_test.py
Fairly quick fix, just altered upper limit of ranges in RGB Nodes/Predicates to 256 instead of 255.
> 1113 rgbcolornodepredicate are slightly bugged

- scripts/count_stroke_samples.py
- scripts/downsample_curriculum.py
Closes #1147
Added two scripts: `count_stroke_samples.py` which counts the number of objects in an input curriculum which have stroke graphs, and `downsample_curriculum.py`, which takes as an input a preexisting reorganized curriculum and copies up to `k` samples per object to create a new training curriculum.
> 1147 generate downsampled objects

- adam/axis.py
- adam/geon.py
- adam/ontology/__init__.py
- adam/ontology/phase1_spatial_relations.py
- adam/perception/__init__.py
- adam/perception/developmental_primitive_perception.py
- adam/perception/perception_graph.py
- adam/perception/perception_graph_nodes.py
- adam/semantics.py
Closes #1134
In order to eliminate the need for a large `if..elif..else` chain, we define a `dot_label()` function for all classes which can be represented in `_to_dot_node()`
> Move all labels to dot_label function

- adam_preprocessing/shape_stroke_extraction.py
I originally just fixed the shape of `img_tmp` but as far as i can tell we never use it, so we can delete it to fix the crash.
> Stroke extraction: Fix crash when seg. image is larger than 256x256

- adam/flask_backend/app.py
In the changes in #1161, we added logic to abort the `get_scene` and `get_image` API calls when any individual component of the call was missing, but this logic was faulty and aborted whenever we request contents of a directory with scene number 0 since we detect 0 to be `false`. This PR patches that error and adds logic to abort if an invalid (negative) scene number is requested.
> Fix dropped requests for situation_0 scenes

- adam/curriculum/curriculum_from_files.py
- adam/perception/visual_perception.py
- adam_preprocessing/shape_stroke_graph_inference.py
- adam_preprocessing/shape_stroke_graph_learner.py
- adam_preprocessing/utils.py
- parameters/experiments/p3/m5_objects_v0_with_mugs_full_subset.params
- parameters/experiments/p3/m6_objects_v0_with_mugs_10pertype_subset.params
- parameters/experiments/p3/m6_objects_v0_with_mugs_2pertype_subset.params
- parameters/experiments/p3/m6_objects_v0_with_mugs_top2.params
- parameters/experiments/p3/m6_objects_v0_with_mugs_top3.params
- parameters/experiments/p3/m6_objects_v0_with_mugs_top4.params
- parameters/experiments/p3/m6_objects_v0_with_mugs_top5.params
- parameters/experiments/p3/m6_unknown_objects.params
- scripts/GNN_topk_analysis.py
- scripts/GNN_vs_expected.py
- scripts/adam_decode_vs_expected.py
Closes #1156 and #1157 
Performed both within the same branch because I needed similar scripts for both for visualizing GNN/ADAM performance between different experiments.
There are 4 important features added here:
1. Script to generate confusion matrix for GNN outputs given an input curriculum
2. Script to generate confusion matrix for ADAM outputs given an input curriculum
3. Script to generate confusion matrix for top GNN outputs per object given an input curriculum
4. Added functionality to
- Retrieve top `k` GNN decodes per object from `shape_stroke_graph_inference.py`
- Add each of the top `k` decodes as a node in ADAM and handle accordingly.
Aside from those, most of the new additions here are just adding parameter files which I used the preexisting downsample/unknown object …
> 1156 downsampling experiment

- angular-viewer/adam-angular-demo/src/app/components/panel-viewer/panel-viewer.component.ts
Fixes a bug in the front end where the panel at the bottom of the page displaying object similarities/differences lingers when submitting new requests for scenes with no differences present. We now check for cases where there are no differences, and then explicitly clear/hide the difference panel.
> Remove similarity panel if no data is provided

- adam_preprocessing/utils.py
[Optional parameters](https://docs.python.org/3/library/typing.html#typing.Optional) should default to `None`. Otherwise this function has to be explicitly called with `None` as the value for `dir_num`.
> Optional param defaults to None

- adam_preprocessing/shape_stroke_extraction.py
Alternative to #1176 where we fix the code instead of the README.
@boyleconnor Let me know if this fixes the problem on your end.
> Add absolute dirs to MATLAB path to make stroke extraction independent of working dir

- adam_preprocessing/shape_stroke_graph_inference.py
- adam_preprocessing/shape_stroke_graph_learner.py
- adam_preprocessing/utils.py
Closes #1187. I've tested this briefly and it seems to fix the crash. I tested on the "M5 objects v0 with mugs" curriculum both single-object and multi-object. I also tested with the live demo, using both "good" examples and some examples where we know we won't get any strokes.
> Fix GNN decode when some situations are missing stroke output

- README.md
- adam/experiment/run_pipeline.py
- adam_preprocessing/color_refine_curriculum.py
- adam_preprocessing/color_refinement.py
- adam_preprocessing/color_segment_curriculum.py
- adam_preprocessing/color_segment_curriculum.sh
- adam_preprocessing/color_segmentation.py
- adam_preprocessing/extract_strokes.sh
- adam_preprocessing/mask_image.py
- adam_preprocessing/shape_stroke_extraction.py
- parameters/experiments/p3/m6_pipeline_debug.params
- slurm/adam.sh
- slurm/segment.sh
Implements a script to queue all preprocessing steps from one script. The preprocessing steps are queued as separate Slurm jobs with dependencies on each other, set up to cancel immediately if one of their dependencies is canceled/fails. This script can also supports running each step iteratively and interactively by running the Slurm scripts in Bash.
I haven't yet tested this with color segmentation or instance segmentation. Once I have both working I may add segmentation server startup to this.
> Pipeline script

- scripts/reorganize_curriculum.py
This should address the problem where we don't include all of ASU's output situations in our curriculum. Including everything makes proper analysis simpler since we don't have to explicitly factor in the `x` situations that were lacking strokes. Also because of differences between ASU's and our stroke extraction output we may be able to use those `x` situations after all -- especially given we're using a different, out-of-AirSim way of segmenting.
> Add flag to drop situations with no strokes

- adam/experiment/run_pipeline.py
- parameters/experiments/p3/m6_pipeline_debug.params
- slurm/segment.sh
One addition and two fixes to the pipeline code:
1. Option to allow copying segmentation files from the base curriculum. This is mainly to allow us to run the AirSIm experiments. However, it's also a way of reusing "pre-baked" segmentations for a curriculum, which could be useful because of how long segmentation takes.
2. Fix the `job_logs_path` parameter type so that the job logs dir is always created. This prevents submission errors when running Slurm jobs.
3. Increases time limit for segmentation Slurm script.
> Pipeline updates

- adam/learner/attributes.py
- adam/learner/objects.py
- adam/learner/perception_graph_template.py
- adam/learner/plurals.py
- adam/learner/relations.py
- adam/learner/verbs.py
- adam/perception/perception_graph.py
The crash happened because we were actually updating the new hypothesis created from the current perception, rather than updating the old hypothesis.
> Fix crash when learner hypothesis and perception have continuous nodes

- adam_preprocessing/shape_stroke_extraction.py
Account for no objects detected in the stroke extraction code so we don't make an image of size 0.
> Account for no objects detected in stroke extraction code

- adam/curriculum/filter_curriculum.py
- adam/curriculum/organize_objects.py
- adam/experiment/run_pipeline.py
- parameters/experiments/p6_isi/m5_isi_rcnn.params
- parameters/experiments/p6_isi/m5_isi_stego.params
- parameters/experiments/p6_isi/m6_isi_rcnn.params
- parameters/experiments/p6_isi/m6_isi_stego.params
- parameters/experiments/p6_isi/m6_isi_test.params
- slurm/filter_curriculum.sh
This PR adds a script to transform a directory of images into an ADAM curriculum along a given train/test split. 
Additionally this adds the params for the M6 Stego/RCNN experiments along with other bug fixes to support.
> Organize new curriculum

- adam_preprocessing/shape_stroke_extraction.py
Fixes another crash along the lines of #1226.
> Prevent crash when attempting to combine empty stroke extraction result
